### ISSUE TITLE
Non determinism in `random_crystal` as the seed kwarg isn't used.

### ISSUE THREAD

**Issue by CompRhys** [MaterSim/PyXtal#263]
the `pyxtal.from_random()` has a kwarg `seed` but this is only used in the generation of molecular crystals. It would be very helpful to make this deterministic given the seed in order to allow downstream testing. Given the nature of a random crystal allowing higher symmetry than expected in order to have consistent (but brittle) tests we need the ability to identify a lottery ticket seed and fix that for the purposes of testing.

**Comment by qzhu2017** [comment]
@CompRhys 
Thanks.

You can just setup the random seeds before you call pyxtal as follows

```python
import numpy as np
import random
random.seed(0)
np.random.seed(0)

from pyxtal import pyxtal
xtal = pyxtal()
for i in range(10):
    xtal.from_random(3, 19, ['C'], [4])
    print(i, xtal.lattice)
```

**Comment by CompRhys** [comment]
would you be open to refactoring such that that they take locally scoped rng from `np.random.default_rng()` calls in relevant places?

Not sure I have bandwidth to do it right away but should be able to do it in the medium term

**Comment by qzhu2017** [comment]
@CompRhys 
You can probably add it in __init__.py
https://github.com/qzhu2017/PyXtal/blob/777ab9e1bb6a29030178604dfe1fe626e54969ee/pyxtal/__init__.py#L173

```python
def __init__(self, molecular=False, seed=None):
    if seed is not None:
        random.seed(seed)
        np.random.seed(seed)
```

**Comment by CompRhys** [comment]
that sort of solution affects the global seed though which can have unintended interactions with other parts of code outside the package hence why I would want to use locally scoped PRNGs to be safer

**Comment by qzhu2017** [comment]
I see. Just make sure that the random.seed also needs to be fixed. PyXtal used both random and np.random. So we need to set two needs in order to guarantee the reproducibility.
