### ISSUE TITLE
pyxtal.from_seed() fails

### ISSUE THREAD

**Issue by kazeevn** [MaterSim/PyXtal#275]
Hello! `pyxtal.from_seed()` fails for a Pymatgen structure with `AttributeError: 'NoneType' object has no attribute 'international'`. Reducing tolerance removes the error. Attaching the example.
[debug_pyxtal.zip](https://github.com/user-attachments/files/17178633/debug_pyxtal.zip)
[requirements.txt](https://github.com/user-attachments/files/17178634/requirements.txt)

Libraries versions are the latest:
```
pyxtal==1.0.3
pymatgen==2024.9.17.1
spglib==2.5.0
```

**Comment by kazeevn** [comment]
One more structure that fails with `tol=0.1`, but succeeds with a lower one.
[009617.json](https://github.com/user-attachments/files/17187556/009617.json)

**Comment by qzhu2017** [comment]
@kazeevn 
Hi, the symmetry is determined from Spglib. Please just add try-exception to skip these structures. We don't have a plan to fix this issue in PyXtal.
