### ISSUE TITLE
Typo in HM_Full.csv database

### ISSUE THREAD

**Issue by kbarros** [MaterSim/PyXtal#278]
There is a typo in the HM_Full.csv database on this line:
https://github.com/MaterSim/PyXtal/blob/1ba044cace1815d450e476a1fcb2fe8cb5798923/pyxtal/database/HM_Full.csv#L53

In particular, the P and P^-1 data for setting "C n 1 1" of spacegroup 9 should be corrected as follows:
```
52,9,9:a2,C n 1 1,"b,a,-a-c","b,a,-b-c",1
```

Currently, the P operation is incorrectly listed as `"-b,a,c"`, but it should be `"b,a,-a-c"`. Note that `P = "-b,a,c"` is already listed for a different setting, "C c 1 1".

These correct P and P^-1 can be verified from the Bilbao server. Go to the [Wyckoff positions page](https://www.cryst.ehu.es/cryst/get_wp.html) enter spacegroup 9, and click "ITA setting". A list of options will appear showing all P and P^-1. Clicking on the [setting "C n 1 1"](https://www.cryst.ehu.es/cgi-bin/cryst/programs//nph-trgen?gnum=009&what=wpos&trmat=b,a,-a-c&unconv=C%20n%201%201%20[%20%3Ci%3Ecell%20choice%202%3C/i%3E%20]&from=ita) gives additional information.

The P operator string for every Hall number 1..530 _besides_ 52 seems to be OK.

**Comment by qzhu2017** [comment]
@kbarros  Wow! Thanks for pointing out this issue. I will keep this issue open after running a systematic check with the Bilbao server.

**Comment by kbarros** [comment]
Sounds good. I really appreciate that you compiled these tables in PyXtal. I think they will be useful more broadly.

By the way, the PyXtal tables now pass the following test: Loop over every possible setting (Hall numbers 1..530), associated with a group `g1`. Map to the ITA standard setting, giving group `g2`. Load the symmetry operations for both groups from the spglib database. Verify that the affine transformation `P` maps group `g2` into `g1`. That is, check `[inv(P) * s * P for s in g2] ≈ g1` for the appropriate notion of group equality (set equivalence up to mod 1 in translations).

The code is here:
https://github.com/SunnySuite/Sunny.jl/blob/ad2aae71419454f4c860ac76834eddee8b1295de/test/test_symmetry.jl#L121-L131
